#Switch modes for how Zombies are managed
#Modes Are: float OR drown
#
#Float: Zombies will automatically attempt to swim up when it water using Path Goals
#     - This does mean zombies will not try to target players in water
#Drown: Zombies will die if they are turned into Drowned instead of converted
#     - Normal functionality just no Drowned spawn.
stop-mode: float